#!/bin/bash
#
PathToCapturePrint=~/.dosbox         # Where the CapturePrint script is.

# Set-up printing
echo Setting-up printing
$PathToCapturePrint/CapturePrint &

# Run DOSBox-X
dosbox-x "$@"                        # Add path to binary if needed.

#Cancel printing
echo Switch off printing
killall CapturePrint

exit 0

